Table PACIENTE {
    CPF int [pk, increment] // PK
    Nome varchar
}

Table CONSULTA {
    Id_consulta int [pk, increment] // PK
    CPF_paciente int [ref: - PACIENTE.CPF] // FK
    data_consulta date
    descricao varchar
}